---
config:
  layout: dagre
---
flowchart TD
    A[Users / Clients] --> B[DNS]
    B[DNS] --> D["Send HTTP Request to 8.8.8.8"]
    D --> E["Nginx Web Server on Server"]
    E --> F["Application Server"] & A
    F --> G["Application Code - PHP Files"] & H["MySQL Database"] & E
    H --> F
    G --> F
